# Generated by Django 5.0.3 on 2024-03-15 18:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='quarterMatch',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
